name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  trading_engine_job:
    build:

      runs-on: ubuntu-latest
      defaults:
        run:
          working-directory: ./src/TradingEngine_Application
      steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x # We are targeting netcoreapp3.1.
      - name: Restore dependencies
        run: dotnet restore
      - name: Build_TradingEngine
        run: dotnet build TradingEngine.sln --no-restore
      - name: Test_TradingEngine
        run: dotnet test TradingEngine.sln --no-build --verbosity normal
  trading_client_job:
      build:

      runs-on: ubuntu-latest
      defaults:
        run:
          working-directory: ./src/TradingClient_Application/Console/ConsoleTradingClient
      steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x # We are targeting netcoreapp3.1.
      - name: Restore dependencies
        run: dotnet restore
      - name: Build_ConsoleTradingClient
        run: dotnet build ConsoleTradingClient.sln --no-restore
      - name: Test_ConsoleTradingClient
        run: dotnet test ConsoleTradingClient.sln --no-build --verbosity normal

