name: .NET Console Trading Client

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/TradingClient_Application/Console/ConsoleTradingClient
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x # We are targeting netcoreapp3.1.
    - name: Restore dependencies
      run: dotnet restore
    - name: Build_ConsoleTradingClient
      run: dotnet build ConsoleTradingClient.sln --no-restore
    - name: Test_ConsoleTradingClient
      run: dotnet test ConsoleTradingClient.sln --no-build --verbosity normal

